# build an runtime instructions for seafile syncer
version: '3'

services:
  user1: &base
    image: sternmotor/seafile-sync:23.03
    environment: 
      SERVER_URL: 'https://seafile.example.com'
      PASSWORD_FILE: '/var/run/secrets/seafile'
      USERNAME: 'user1@example.com'
      RESTART_DELAY: 1800
    volumes:
    - data:/seafile-data:rw
    secrets:
    - seafile
    build:
      context: .
      args:
        CONTAINER_UID: 1000
        CONTAINER_GID: 1000
    restart: unless-stopped

volumes:
  data:


secrets:
  seafile:
    file: $PWD/secrets/seafile

# vim:sw=2:ts=2:sts=2:et:
